export const WORKBOOK_TEMPLATE = {
  tasks: [
    {
      module: 'CONSULTANCY',
      phase: 'PRE-DESIGN',
      work_name: 'EXISTING LAYOUT',
      details: '',
      sort_order: 0,
    },
    {
      module: 'CONSULTANCY',
      phase: 'PRE-DESIGN',
      work_name: 'PROPOSED LAYOUT',
      details: 'LAYOUT FINALISATION',
      sort_order: 1,
    },
    {
      module: 'CONSULTANCY',
      phase: 'PRE-DESIGN',
      work_name: 'REFERENCE PRESENTATION & MOODBOARD',
      details: '',
      sort_order: 2,
    },
    {
      module: 'CONSULTANCY',
      phase: 'PRE-DESIGN',
      work_name: 'PITCH PROPOSAL',
      details: '',
      sort_order: 3,
    },
    {
      module: 'CONSULTANCY',
      phase: 'PRE-DESIGN',
      work_name: 'CONCEPT DESIGN 01-3D',
      details: '',
      sort_order: 4,
    },
    {
      module: 'CONSULTANCY',
      phase: 'DESIGN',
      work_name: 'CONCEPT DESIGN 02-3D',
      details: 'WITH MATERIAL',
      sort_order: 5,
    },
    {
      module: 'CONSULTANCY',
      phase: 'DESIGN',
      work_name: 'DESIGN DEVELOPMENT 01',
      details: '',
      sort_order: 6,
    },
    {
      module: 'CONSULTANCY',
      phase: 'DESIGN',
      work_name: 'DESIGN DEVELOPMENT 02',
      details: 'WITH MATERIAL',
      sort_order: 7,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'TILE SELECTION',
      sort_order: 8,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'FLOORING',
      sort_order: 9,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'FURNITURE + MILL WORK',
      sort_order: 10,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'FURNITURE + MILL WORK-MATERIAL SELECTION',
      sort_order: 11,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'STONE JAMBS',
      sort_order: 12,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'WALL PAINTS',
      sort_order: 13,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'LOOSE FURNITURE',
      sort_order: 14,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'ARCHITECTURAL LIGHTING(INCLUDING FANS)',
      sort_order: 15,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'APPLIANCES',
      sort_order: 16,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'WALL HIGHLIGHTERS',
      sort_order: 17,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'SOFT FURNISHING',
      sort_order: 18,
    },
    {
      module: 'CONSULTANCY',
      phase: 'MATERIAL SELECTION',
      work_name: '',
      details: 'DÉCOR SELECTION',
      sort_order: 19,
    },
    {
      module: 'CONSULTANCY',
      phase: 'TENDER DRAWINGS',
      work_name: 'BUILDING LAYOUT',
      details: 'FLOOR LAYOUT + DEMOLITION LAYOUT',
      sort_order: 20,
    },
    {
      module: 'CONSULTANCY',
      phase: 'TENDER DRAWINGS',
      work_name: 'BUILDING SECTION & ELEVATION',
      details: '',
      sort_order: 21,
    },
    {
      module: 'CONSULTANCY',
      phase: 'TENDER DRAWINGS',
      work_name: 'CIVIL LAYOUT',
      details: '',
      sort_order: 22,
    },
    {
      module: 'CONSULTANCY',
      phase: 'TENDER DRAWINGS',
      work_name: 'ELECTRICAL LAYOUT',
      details: '',
      sort_order: 23,
    },
    {
      module: 'CONSULTANCY',
      phase: 'TENDER DRAWINGS',
      work_name: 'PLUMBING LAYOUT',
      details: '',
      sort_order: 24,
    },
    {
      module: 'CONSULTANCY',
      phase: 'TENDER DRAWINGS',
      work_name: 'AC/HVAC LAYOUT',
      details: '',
      sort_order: 25,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'DEMOLITION DETAILING',
      details: '',
      sort_order: 26,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'CIVIL DETAILING + STRUCTURE LAYOUT',
      details: '',
      sort_order: 27,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'DOOR WINDOW SCHEDULE + STONE JAMBS',
      details: '',
      sort_order: 28,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'FLOOR LAYOUT & FLOORING DETAILS',
      details: '',
      sort_order: 29,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'BATHROOM DETAILS',
      details: '',
      sort_order: 30,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'CEILING LAYOUT AND DETAILING',
      details: '',
      sort_order: 31,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'WALL ELEVATION',
      details: '',
      sort_order: 32,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'FIXED FURNITURE DETAILS',
      details: 'KITCHEN',
      sort_order: 33,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'FIXED FURNITURE DETAILS',
      details: 'TV UNIT',
      sort_order: 34,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'FIXED FURNITURE DETAILS',
      details: 'WARDROBE',
      sort_order: 35,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'FIXED FURNITURE DETAILS',
      details: 'STORAGE',
      sort_order: 36,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'FIXED FURNITURE DETAILS',
      details: 'CROCKERY',
      sort_order: 37,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'FIXED FURNITURE DETAILS',
      details: 'BAR UNIT',
      sort_order: 38,
    },
    {
      module: 'CONSULTANCY',
      phase: 'WORKING DRAWINGS',
      work_name: 'FIXED FURNITURE DETAILS',
      details: 'BED BACK',
      sort_order: 39,
    },
    {
      module: 'PMC',
      phase: 'SITE PREPRATION',
      work_name: 'DEMOLITION',
      details: '',
      sort_order: 0,
    },
    {
      module: 'PMC',
      phase: 'SITE PREPRATION',
      work_name: 'SITE CLEARING',
      details: '',
      sort_order: 1,
    },
    {
      module: 'PMC',
      phase: 'SITE PREPRATION',
      work_name: 'SOIL TESTING',
      details: '',
      sort_order: 2,
    },
    {
      module: 'PMC',
      phase: 'SITE PREPRATION',
      work_name: 'WATER TABLE TEST',
      details: '',
      sort_order: 3,
    },
    {
      module: 'PMC',
      phase: 'SITE PREPRATION',
      work_name: 'DRAINAGE TEST',
      details: '',
      sort_order: 4,
    },
    {
      module: 'PMC',
      phase: 'SITE PREPRATION',
      work_name: 'EXCAVATION',
      details: '',
      sort_order: 5,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'FOUNDATION',
      details: '',
      sort_order: 6,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'COLUMN & BEAM LAYING',
      details: '',
      sort_order: 7,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'SLAB + SERVICE CORE',
      details: '',
      sort_order: 8,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'SHUTTERING/FOAM WORK',
      details: 'CONCRETE & RCC',
      sort_order: 9,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'WALLING',
      details: '',
      sort_order: 10,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'ELECTRICAL',
      details: '',
      sort_order: 11,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'PLUMBING',
      details: '',
      sort_order: 12,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'MECHANICAL',
      details: '',
      sort_order: 13,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'DOOR FRAME WORK',
      details: '',
      sort_order: 14,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'BATHROOM WATERPROOFING',
      details: '',
      sort_order: 15,
    },
    {
      module: 'PMC',
      phase: 'CIVIL WORK',
      work_name: 'TERMITE TREATMENT',
      details: '',
      sort_order: 16,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'METAL WORK',
      details: '',
      sort_order: 17,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'FLOORING',
      details: '',
      sort_order: 18,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'BATHROOM TILES',
      details: '',
      sort_order: 19,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'STONE JAMBS',
      details: '',
      sort_order: 20,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'FALSE CEILING',
      details: '',
      sort_order: 21,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'MILL WORK',
      details: 'KITCHEN, BED BACK,WARDROBE & STORAGE',
      sort_order: 22,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'ELECTRICAL',
      details: 'LIGHT INSTALLATION',
      sort_order: 23,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: '',
      details: 'SWITCH BOARDS',
      sort_order: 24,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'WALL PANELLING',
      details: '',
      sort_order: 25,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'PAINT',
      details: '1ST BASE COAT + PRIMER',
      sort_order: 26,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: '',
      details: 'DOOR PAINT/POLISH',
      sort_order: 27,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'ELECTRICAL',
      details: 'AC INTALLATION',
      sort_order: 28,
    },
    {
      module: 'PMC',
      phase: 'FIT OUTS',
      work_name: 'STONE POLISH',
      details: '',
      sort_order: 29,
    },
    {
      module: 'PMC',
      phase: 'FINISHING',
      work_name: 'PAINT',
      details: '2ND COAT',
      sort_order: 30,
    },
    {
      module: 'PMC',
      phase: 'FINISHING',
      work_name: 'WINDOW INSTALLATION',
      details: '',
      sort_order: 31,
    },
    {
      module: 'PMC',
      phase: 'FINISHING',
      work_name: 'CP FITTINGS & SANITARY',
      details: '',
      sort_order: 32,
    },
    {
      module: 'PMC',
      phase: 'FINISHING',
      work_name: 'HARDWARE INSTALLATION',
      details: '',
      sort_order: 33,
    },
    {
      module: 'PMC',
      phase: 'FINISHING',
      work_name: 'PAINT',
      details: 'FINAL PAINT COAT',
      sort_order: 34,
    },
    {
      module: 'PMC',
      phase: 'FINISHING',
      work_name: 'ELECTRICAL',
      details: 'METER INSTALLATION',
      sort_order: 35,
    },
    {
      module: 'PMC',
      phase: 'FINISHING',
      work_name: 'CLEANING',
      details: '',
      sort_order: 36,
    },
    {
      module: 'PMC',
      phase: 'SNAG & HANDOVER',
      work_name: 'SNAG LIST',
      details: '',
      sort_order: 37,
    },
    {
      module: 'PMC',
      phase: 'SNAG & HANDOVER',
      work_name: 'DEEP CLEANING AND STYLING',
      details: '',
      sort_order: 38,
    },
  ],
  procurement: [
    {
      item_type: 'MATERIAL',
      category_name: 'TILES',
      sort_order: 0,
    },
    {
      item_type: 'MATERIAL',
      category_name: 'FURNITURE',
      sort_order: 1,
    },
    {
      item_type: 'MATERIAL',
      category_name: 'MILL WORK-MATERIAL',
      sort_order: 2,
    },
    {
      item_type: 'MATERIAL',
      category_name: 'STONE JAMBS',
      sort_order: 3,
    },
    {
      item_type: 'MATERIAL',
      category_name: 'WALL PAINTS',
      sort_order: 4,
    },
    {
      item_type: 'MATERIAL',
      category_name: 'LOOSE FURNITURE',
      sort_order: 5,
    },
    {
      item_type: 'MATERIAL',
      category_name: 'ARCHITECTURAL LIGHTING(INCLUDING FANS)',
      sort_order: 6,
    },
    {
      item_type: 'MATERIAL',
      category_name: 'APPLIANCES',
      sort_order: 7,
    },
    {
      item_type: 'MATERIAL',
      category_name: 'WALL HIGHLIGHTERS',
      sort_order: 8,
    },
    {
      item_type: 'MATERIAL',
      category_name: 'SOFT FURNISHING',
      sort_order: 9,
    },
    {
      item_type: 'MATERIAL',
      category_name: 'DÉCOR',
      sort_order: 10,
    },
    {
      item_type: 'LABOUR',
      category_name: 'CIVIL',
      sort_order: 11,
    },
    {
      item_type: 'LABOUR',
      category_name: 'ELECTRICAL',
      sort_order: 12,
    },
    {
      item_type: 'LABOUR',
      category_name: 'PLUMBING',
      sort_order: 13,
    },
    {
      item_type: 'LABOUR',
      category_name: 'MECHANICAL/HVAC/AC',
      sort_order: 14,
    },
    {
      item_type: 'LABOUR',
      category_name: 'METAL',
      sort_order: 15,
    },
    {
      item_type: 'LABOUR',
      category_name: 'TILING',
      sort_order: 16,
    },
    {
      item_type: 'LABOUR',
      category_name: 'FALSE CEILING',
      sort_order: 17,
    },
    {
      item_type: 'LABOUR',
      category_name: 'MILL WORK',
      sort_order: 18,
    },
    {
      item_type: 'LABOUR',
      category_name: 'PAINTING',
      sort_order: 19,
    },
    {
      item_type: 'LABOUR',
      category_name: 'GLASS& WINDOW',
      sort_order: 20,
    },
    {
      item_type: 'LABOUR',
      category_name: 'LANDSCAPE',
      sort_order: 21,
    },
  ],
};
