-- Consolidated migration for the supplied Percona/MySQL 5.7.23 schema.
-- Stop application/worker writes and take an external backup before running.
-- Execute this whole file in HeidiSQL/MySQL, with DELIMITER support.
-- UUID defaults are generated by Sequelize; MySQL 5.7 cannot use UUID() defaults.
-- No table is truncated or dropped. Original tables, indexes, timestamps and
-- UUIDs are retained. Numeric identities and relational references are mapped.
-- DDL implicitly commits. Rerun this file to resume an interrupted migration.
-- Do not run the earlier .cjs runner as an additional migration on this schema.
-- The pasted dump already includes the brief classification and room_type_other
-- columns. The guards below also support installations missing those columns.
-- The terms/plain-text-input changes require no database column changes.

USE `spsyn8lm_rippotai_erp`;
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `_uuid_pk_id_map` (
  `table_name` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `old_id` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `uuid_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`table_name`, `old_id`), KEY `idx_uuid_map_new` (`table_name`, `uuid_id`)
) ENGINE=InnoDB;

-- Only needed if workflow rows reference legacy INTEGER project IDs.
-- Populate verified old-project -> existing projects.id values before CALL below.
-- Never guess them from project names or the example/demo ordering.
CREATE TABLE IF NOT EXISTS `_uuid_project_id_map` (
  `old_id` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `project_id` char(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`old_id`)
) ENGINE=InnoDB;
-- Example format only (replace with verified values if required):
-- INSERT INTO _uuid_project_id_map VALUES ('OLD_NUMERIC_ID', 'EXISTING_PROJECT_UUID');

CREATE TABLE IF NOT EXISTS `_uuid_20261006_state` (
  `id` tinyint NOT NULL PRIMARY KEY,
  `status` varchar(20) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS `_uuid_20261006_targets` (
  `table_name` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL PRIMARY KEY,
  `row_count` bigint unsigned DEFAULT NULL,
  `backup_done` tinyint NOT NULL DEFAULT 0,
  `convert_pk` tinyint NOT NULL DEFAULT 1
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS `_uuid_20261006_refs` (
  `table_name` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `source_column` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `target_column` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `parent_table` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `filter_column` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `filter_value` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `nullable` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`table_name`, `target_column`)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS `_uuid_20261006_fks` (
  `table_name` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `constraint_name` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `restore_sql` text NOT NULL,
  PRIMARY KEY (`table_name`, `constraint_name`)
) ENGINE=InnoDB;

DELIMITER $$
DROP PROCEDURE IF EXISTS `_uuid57_exec`$$
CREATE PROCEDURE `_uuid57_exec`(IN p_sql LONGTEXT)
BEGIN
  SET @uuid57_sql = p_sql;
  PREPARE uuid57_stmt FROM @uuid57_sql;
  EXECUTE uuid57_stmt;
  DEALLOCATE PREPARE uuid57_stmt;
END$$

DROP PROCEDURE IF EXISTS `_uuid57_add`$$
CREATE PROCEDURE `_uuid57_add`(IN p_table VARCHAR(64), IN p_column VARCHAR(64), IN p_definition TEXT)
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = p_table)
     AND NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = p_table AND COLUMN_NAME = p_column) THEN
    CALL _uuid57_exec(CONCAT('ALTER TABLE `', p_table, '` ADD COLUMN `', p_column, '` ', p_definition));
  END IF;
END$$

DROP PROCEDURE IF EXISTS `_uuid57_ref`$$
CREATE PROCEDURE `_uuid57_ref`(IN p_table VARCHAR(64), IN p_snake VARCHAR(64), IN p_camel VARCHAR(64), IN p_parent VARCHAR(64), IN p_filter VARCHAR(64), IN p_value VARCHAR(64))
BEGIN
  DECLARE v_source VARCHAR(64);
  DECLARE v_nullable VARCHAR(3);
  SET v_source = NULL;
  IF EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = p_table AND COLUMN_NAME = p_snake) THEN
    SET v_source = p_snake;
  ELSEIF p_camel IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = p_table AND COLUMN_NAME = p_camel) THEN
    SET v_source = p_camel;
  END IF;
  IF v_source IS NOT NULL THEN
    SELECT IS_NULLABLE INTO v_nullable FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = p_table AND COLUMN_NAME = v_source;
    INSERT IGNORE INTO _uuid_20261006_refs
      (table_name, source_column, target_column, parent_table, filter_column, filter_value, nullable)
      VALUES (p_table, v_source, p_snake, p_parent, p_filter, p_value, v_nullable);
  END IF;
END$$

DROP PROCEDURE IF EXISTS `_uuid57_rename`$$
CREATE PROCEDURE `_uuid57_rename`(IN p_table VARCHAR(64), IN p_old VARCHAR(64), IN p_new VARCHAR(64), IN p_definition TEXT)
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = p_table AND COLUMN_NAME = p_old)
    AND NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = p_table AND COLUMN_NAME = p_new) THEN
    CALL _uuid57_exec(CONCAT('ALTER TABLE `', p_table, '` CHANGE COLUMN `', p_old, '` `', p_new, '` ', p_definition));
  END IF;
END$$
DELIMITER ;

-- Missing workflow tables are created with their final UUID schema.
-- Their foreign keys are installed only after the existing integer IDs migrate.
CREATE TABLE IF NOT EXISTS `phases` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(255) NOT NULL, `code` varchar(40) NOT NULL,
  `track_type` enum('MAIN','VENDOR_TRADES','MATERIAL_PROCUREMENT') NOT NULL DEFAULT 'MAIN',
  `order` int NOT NULL, `description` text,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_workflow_phases_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE IF NOT EXISTS `deliverables` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `step_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(200) NOT NULL, `description` text,
  `is_required` tinyint(1) NOT NULL DEFAULT 1, `file_type` varchar(60) DEFAULT NULL,
  `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`), KEY `idx_deliverables_step` (`step_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE IF NOT EXISTS `gate_logs` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `project_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `step_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `gate_name` varchar(150) NOT NULL, `achieved_at` datetime NOT NULL,
  `approver_team_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `approver_name` varchar(150) NOT NULL, `notes` text,
  `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`), KEY `idx_workflow_gate_project` (`project_id`),
  KEY `idx_workflow_gate_step` (`step_id`), KEY `idx_workflow_gate_team` (`approver_team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE IF NOT EXISTS `continuity_roles` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `project_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `team_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `continuity_type` enum('CONTINUOUS','GATE_BOUND') NOT NULL DEFAULT 'CONTINUOUS',
  `opens_at_step_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `closes_at_step_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `actual_opened_at` datetime DEFAULT NULL, `actual_closed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`), KEY `idx_continuity_project` (`project_id`), KEY `idx_continuity_team` (`team_id`),
  KEY `idx_continuity_open_step` (`opens_at_step_id`), KEY `idx_continuity_close_step` (`closes_at_step_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_step_progress` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `project_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `step_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `status` enum('NOT_STARTED','IN_PROGRESS','COMPLETED','BLOCKED') NOT NULL DEFAULT 'NOT_STARTED',
  `assignee_team_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `assignee_name` varchar(150) DEFAULT NULL,
  `planned_start_date` date DEFAULT NULL, `planned_end_date` date DEFAULT NULL,
  `actual_start_date` datetime DEFAULT NULL, `actual_completion_date` datetime DEFAULT NULL,
  `signed_off_by` varchar(150) DEFAULT NULL, `signed_off_at` datetime DEFAULT NULL,
  `blocked_reason` text, `notes` text,
  `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_workflow_progress_project_step` (`project_id`,`step_id`),
  KEY `idx_workflow_progress_step` (`step_id`), KEY `idx_workflow_progress_team` (`assignee_team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_deliverable_records` (
  `id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `project_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `deliverable_id` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `is_submitted` tinyint(1) NOT NULL DEFAULT 0,
  `submitted_at` datetime DEFAULT NULL, `file_url` varchar(500) DEFAULT NULL,
  `submitted_by` varchar(150) DEFAULT NULL, `version` varchar(20) DEFAULT NULL,
  `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_workflow_record_project_deliverable` (`project_id`,`deliverable_id`),
  KEY `idx_workflow_record_deliverable` (`deliverable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CALL _uuid57_add('site_recce_rooms', 'room_type_other', 'VARCHAR(255) NULL');
CALL _uuid57_add('project_briefs', 'project_category', 'ENUM(''RESIDENTIAL'',''COMMERCIAL'',''INSTITUTIONAL'') NULL');
CALL _uuid57_add('project_briefs', 'site_type_other', 'TEXT NULL');
CALL _uuid57_add('project_briefs', 'site_condition_other', 'TEXT NULL');
CALL _uuid57_add('teams', 'type', 'ENUM(''ARCHITECT'',''SUPERVISOR'',''ADMIN'',''ACCOUNTS'',''PLANNING'',''PROCUREMENT'',''CLIENT'',''TRADE'') NULL');
CALL _uuid57_add('teams', 'is_trade', 'TINYINT(1) NOT NULL DEFAULT 0');
CALL _uuid57_add('teams', 'trade_category', 'ENUM(''CIVIL'',''ELECTRICAL'',''PLUMBING'',''HVAC'',''CARPENTRY'',''FALSE_CEILING'',''FLOORING'',''PAINTING'',''GLASS_ALUMINIUM'',''METAL_FABRICATION'',''SOFT_FURNISHING'',''LANDSCAPING'') NULL');
CALL _uuid57_add('teams', 'contact_email', 'VARCHAR(150) NULL');
CALL _uuid57_add('teams', 'is_active', 'TINYINT(1) NOT NULL DEFAULT 1');

-- Continue with the journaled migration below.
