-- Apply before deploying the final client brief fields. Existing records stay blank.
ALTER TABLE project_briefs
  ADD COLUMN principal_architect TEXT NULL,
  ADD COLUMN project_lead TEXT NULL,
  ADD COLUMN property_type TEXT NULL,
  ADD COLUMN funding_stage TEXT NULL,
  ADD COLUMN budget_range TEXT NULL,
  ADD COLUMN expected_timeline TEXT NULL,
  ADD COLUMN toilet_facility_and_stay_for_labour TEXT NULL;

ALTER TABLE project_briefs MODIFY COLUMN site_type ENUM('BUILDER_FLOOR','BUNGALOW','VILLA','FARMHOUSE','PENTHOUSE','OFFICE','RETAIL_SHOWROOM','HOTEL','RESTAURANT','BANQUETS','BAR_AND_LOUNGE','CAFE','RESORT','QSR_AND_CLOUD_KITCHEN','CAMPUS_ADDITION','EDUCATION','RELIGIOUS','RESIDENTIAL_INSTITUTIONAL','SPORTS','FLAT','FLOOR','KOTHI','RAW','OTHER') NULL;

ALTER TABLE project_briefs MODIFY COLUMN site_condition ENUM('BARE_PLOT','COLD_SHELL','WARM_SHELL','EXISTING_OCCUPIED','EXISTING_VACANT','EXISTING_OPERATIONAL','REBRANDING','EXISTING_BUILDING_VACANT','EXISTING_BUILDING_OPERATIONAL','FIT_OUT_REQUIRED','OCCUPIED','UNOCCUPIED') NULL;
