-- Apply before deploying the updated brief API. Legacy enum values are preserved.
ALTER TABLE project_briefs
  ADD COLUMN project_category ENUM('RESIDENTIAL','COMMERCIAL','INSTITUTIONAL') NULL,
  ADD COLUMN site_type_other TEXT NULL,
  ADD COLUMN site_condition_other TEXT NULL;

ALTER TABLE project_briefs MODIFY COLUMN site_type ENUM('BUILDER_FLOOR','BUNGALOW','VILLA','FARMHOUSE','PENTHOUSE','OFFICE','RETAIL_SHOWROOM','HOSPITALITY','HOTEL','RESTAURANT','BANQUETS','BAR_AND_LOUNGE','CAFE','RESORT','QSR_AND_CLOUD_KITCHEN','CAMPUS_ADDITION','EDUCATION','RELIGIOUS','RESIDENTIAL_INSTITUTIONAL','SPORTS','FLAT','FLOOR','KOTHI','RAW','OTHER') NULL;
ALTER TABLE project_briefs MODIFY COLUMN site_condition ENUM('BARE_PLOT','COLD_SHELL','WARM_SHELL','EXISTING_OCCUPIED','EXISTING_VACANT','EXISTING_OPERATIONAL','REBRANDING','EXISTING_BUILDING_VACANT','EXISTING_BUILDING_OPERATIONAL','FIT_OUT_REQUIRED','OCCUPIED','UNOCCUPIED','OTHER') NULL;
