export interface FrontendNotificationSource {
  controller: string;
  /** Disambiguates controllers with the same class name. */
  path?: string;
  entity: string;
  label: string;
  actions: Record<string, string>;
  /** Child edits should link to the parent workspace, not the child row. */
  idParam?: string;
  idFields?: string[];
  sharedOnly?: boolean;
  listHandlers?: string[];
}

const crud = { create: 'created', update: 'updated', remove: 'deleted' };

// Explicitly selected user-facing write handlers. This is NOT a model hook or
// a service-name convention: internal helpers, sync jobs, reads, exports,
// previews and validation requests never enter this notification pipeline.
export const FRONTEND_NOTIFICATION_SOURCES: FrontendNotificationSource[] = [
  {
    controller: 'PurchaseOrderController',
    entity: 'purchase_order',
    label: 'Purchase Order',
    actions: { ...crud, approve: 'approved', cancel: 'cancelled' },
  },
  {
    controller: 'WorkOrdersController',
    entity: 'work_order',
    label: 'Work Order',
    actions: {
      ...crud,
      updateStatus: 'status changed',
      approve: 'approved',
      reject: 'rejected',
    },
  },
  {
    controller: 'DeliveryChallanController',
    entity: 'delivery_challan',
    label: 'Delivery Challan',
    actions: { ...crud, receive: 'received' },
  },
  {
    controller: 'InventoryController',
    entity: 'inventory',
    label: 'Inventory',
    actions: {
      create: 'received',
      issue: 'issued',
      adjust: 'adjusted',
      transfer: 'transferred',
      returnMaterial: 'returned',
      receiveFromDelivery: 'received from delivery',
    },
  },
  {
    controller: 'MaterialProcurementController',
    entity: 'material_procurement',
    label: 'Material Procurement',
    actions: { ...crud, submit: 'submitted' },
  },
  {
    controller: 'MaterialRequirementController',
    entity: 'material_requirement',
    label: 'Material Requirement',
    actions: { ...crud, setStatus: 'status changed' },
  },
  {
    controller: 'MaterialEstimateController',
    entity: 'material_estimate',
    label: 'Material Estimate',
    actions: { create: 'created', approve: 'approved', reject: 'rejected' },
  },
  {
    controller: 'MaterialQuotationController',
    entity: 'material_quotation',
    label: 'Material Quotation',
    actions: {
      create: 'created',
      send: 'sent',
      accept: 'accepted',
      reject: 'rejected',
    },
  },
  {
    controller: 'MaterialRateSheetController',
    entity: 'material_rate_sheet',
    label: 'Material Rate Sheet',
    actions: {
      create: 'created',
      approve: 'approved',
      reject: 'rejected',
      remove: 'deleted',
    },
  },
  {
    controller: 'SampleBoardController',
    entity: 'sample_board',
    label: 'Sample Board',
    actions: {
      create: 'created',
      approve: 'approved',
      reject: 'rejected',
      remove: 'deleted',
    },
  },
  {
    controller: 'MaterialMasterController',
    entity: 'material',
    label: 'Material',
    idParam: 'id',
    actions: {
      create: 'created',
      update: 'updated',
      deactivate: 'deactivated',
      addVendor: 'vendor added',
      updateVendor: 'vendor updated',
      removeVendor: 'vendor removed',
      setPreferredVendor: 'preferred vendor changed',
      deactivateVendor: 'vendor deactivated',
      activateVendor: 'vendor activated',
    },
  },
  {
    controller: 'VendorRateComparisonController',
    entity: 'vendor_rate_comparison',
    label: 'Vendor Rate Comparison',
    actions: { create: 'created', update: 'updated' },
  },
  {
    controller: 'ProjectShortlistController',
    entity: 'vendor_shortlist',
    label: 'Vendor Shortlist',
    idParam: 'id',
    actions: { ...crud, saveWorkspaceRow: 'updated' },
  },
  {
    controller: 'ShortlistEntryController',
    entity: 'vendor_shortlist',
    label: 'Shortlist Entry',
    idFields: ['shortlist_id', 'shortlistId', 'projectShortlistId'],
    actions: { ...crud, bulkCreate: 'added', select: 'selected' },
  },
  {
    controller: 'ShortlistPackageController',
    entity: 'shortlist_package',
    label: 'Shortlist Package',
    actions: { create: 'created', apply: 'applied', remove: 'deleted' },
  },
  {
    controller: 'BoqController',
    entity: 'boq',
    label: 'BOQ',
    idParam: 'id',
    listHandlers: ['renameVersion'],
    actions: {
      ...crud,
      combine: 'combined',
      submitForApproval: 'submitted for approval',
      approve: 'approved',
      duplicateVersion: 'version duplicated',
      newVersion: 'version created',
      renameVersion: 'version renamed',
      applyTerms: 'terms updated',
      addCategory: 'category added',
      updateCategory: 'category updated',
      removeCategory: 'category removed',
      addItem: 'item added',
      updateItem: 'item updated',
      removeItem: 'item removed',
      reorderItems: 'items reordered',
      bulkUpdateItems: 'items updated',
      addMiscellaneous: 'charge added',
      updateMiscellaneous: 'charge updated',
      removeMiscellaneous: 'charge removed',
      reorderMiscellaneous: 'charges reordered',
    },
  },
  {
    controller: 'BoqTemplateController',
    entity: 'boq_template',
    label: 'BOQ Template',
    idParam: 'id',
    actions: {
      ...crud,
      addCategory: 'category added',
      deleteCategory: 'category removed',
      addItem: 'item added',
      updateItem: 'item updated',
      deleteItem: 'item removed',
      reorderItems: 'items reordered',
    },
  },
  {
    controller: 'LibraryController',
    path: 'library',
    entity: 'boq_library',
    label: 'BOQ Library',
    actions: {
      createCategory: 'category created',
      createItem: 'item created',
      updateItem: 'item updated',
      removeItem: 'item removed',
    },
  },
  {
    controller: 'PaymentSchedulesController',
    entity: 'payment_schedule',
    label: 'Payment Schedule',
    idParam: 'id',
    actions: {
      ...crud,
      addMilestone: 'milestone added',
      updateMilestone: 'milestone updated',
      removeMilestone: 'milestone removed',
    },
  },
  {
    controller: 'BusinessProposalsController',
    entity: 'business_proposal',
    label: 'Business Proposal',
    actions: { create: 'created', update: 'updated' },
  },
  {
    controller: 'ProjectPlannerController',
    entity: 'project_planner',
    label: 'Project Planner',
    idParam: 'plannerId',
    idFields: ['plannerId', 'planner_id'],
    actions: {
      initializeProjectPlanners: 'initialized',
      createPlanner: 'created',
      updatePlanner: 'updated',
      deletePlanner: 'deleted',
      generatePlannerFromTemplate: 'template applied',
      createPlannerItem: 'item added',
      updatePlannerItem: 'item updated',
      deletePlannerItem: 'item removed',
      attachLocations: 'locations assigned',
      removeLocationFromItem: 'location removed',
      updateItemLocation: 'location updated',
      createProcurementItem: 'procurement item added',
      updateProcurementItem: 'procurement item updated',
      deleteProcurementItem: 'procurement item removed',
    },
  },
  {
    controller: 'ProjectsController',
    entity: 'project',
    label: 'Project Team',
    idParam: 'id',
    actions: {
      addTeamMember: 'member added',
      updateTeamMember: 'member updated',
      removeTeamMember: 'member removed',
    },
  },
  {
    controller: 'TeamController',
    entity: 'team',
    label: 'Team',
    actions: {
      add: 'member added',
      replaceAll: 'roster updated',
      updateMember: 'member updated',
      removeMember: 'member removed',
      createTeam: 'created',
      updateTeam: 'updated',
      activateTeam: 'activated',
      deactivateTeam: 'deactivated',
      deleteTeam: 'deleted',
      addTeamMember: 'member added',
      updateTeamMember: 'member updated',
      makeMemberPrimary: 'primary member changed',
      removeTeamMember: 'member removed',
      createSection: 'section created',
      updateSection: 'section updated',
      deleteSection: 'section removed',
      setSectionAccess: 'access updated',
      bulkSetSectionAccess: 'access updated',
      removeSectionAccess: 'access removed',
    },
  },
  {
    controller: 'RfiController',
    entity: 'rfi',
    label: 'RFI',
    actions: {
      raise: 'raised',
      reroute: 'rerouted',
      respond: 'answered',
      close: 'closed',
    },
  },
  {
    controller: 'MockupController',
    entity: 'mockup',
    label: 'Mockup',
    actions: { propose: 'proposed', review: 'reviewed' },
  },
  {
    controller: 'SiteVisitController',
    entity: 'visit_assignment',
    label: 'Site Visit Assignment',
    actions: {
      createAssignment: 'created',
      updateAssignment: 'updated',
      deactivateAssignment: 'deactivated',
    },
  },
  {
    controller: 'SiteVisitController',
    entity: 'site_visit',
    label: 'Site Visit',
    actions: {
      logVisit: 'logged',
      updateVisit: 'updated',
      checkIn: 'checked in',
    },
  },
  {
    controller: 'SnagController',
    entity: 'snag',
    label: 'Snag',
    actions: { ...crud },
  },
  {
    controller: 'SnagListController',
    entity: 'snag_list',
    label: 'Snag List',
    actions: { create: 'created', update: 'updated' },
  },
  {
    controller: 'DailySiteReportController',
    entity: 'daily_site_report',
    label: 'Daily Site Report',
    actions: { ...crud, share: 'shared' },
  },
  {
    controller: 'AdminDailyReportController',
    entity: 'admin_daily_report',
    label: 'Admin Daily Report',
    actions: { ...crud },
  },
  {
    controller: 'AdminDailyLogController',
    entity: 'admin_daily_report',
    label: 'Admin Daily Log',
    actions: { ...crud },
  },
  {
    controller: 'AdminDprDocumentController',
    entity: 'admin_daily_report',
    label: 'Admin Daily Report',
    actions: { create: 'created' },
  },
  {
    controller: 'QualityChecklistController',
    entity: 'quality_checklist',
    label: 'Quality Checklist',
    idParam: 'checklistId',
    idFields: ['checklistId', 'checklist_id'],
    actions: {
      createChecklist: 'created',
      createFromWorkHead: 'created from template',
      updateChecklist: 'updated',
      deleteChecklist: 'deleted',
      completeChecklist: 'completed',
      addChecklistItem: 'item added',
      bulkUpdateChecklistItems: 'items updated',
      updateChecklistItem: 'item updated',
      deleteChecklistItem: 'item removed',
    },
  },
  {
    controller: 'QualityController',
    entity: 'quality_checklist',
    label: 'Quality Check',
    actions: {
      createItem: 'item created',
      updateItem: 'item updated',
      deactivateItem: 'item deactivated',
      upsert: 'recorded',
    },
  },
  {
    controller: 'ChecklistController',
    entity: 'quality_checklist',
    label: 'Checklist Template',
    actions: { createTemplate: 'created', addItem: 'item added' },
  },
  {
    controller: 'QcSignOffController',
    entity: 'qc_sign_off',
    label: 'Quality Sign-off',
    actions: { recordSignOff: 'recorded' },
  },
  {
    controller: 'VisitStageController',
    entity: 'visit_stage',
    label: 'Visit Stage',
    actions: {
      create: 'created',
      update: 'updated',
      deactivate: 'deactivated',
    },
  },
  {
    controller: 'GatesController',
    entity: 'project_gate',
    label: 'Project Gate',
    idParam: 'projectId',
    actions: {
      clear: 'cleared',
      reopen: 'reopened',
      tick: 'condition updated',
    },
  },
  {
    controller: 'CommandCenterController',
    entity: 'project_gate',
    label: 'Project Workflow',
    idParam: 'projectId',
    actions: { completeTask: 'task completed', approveGate: 'gate approved' },
  },
  {
    controller: 'ProgressController',
    entity: 'project_progress',
    label: 'Project Progress',
    idParam: 'projectId',
    actions: { updateStepProgress: 'updated', signOff: 'step signed off' },
  },
  {
    controller: 'GateController',
    entity: 'project_gate',
    label: 'Workflow Gate',
    idFields: ['projectId', 'project_id'],
    actions: { logGate: 'recorded' },
  },
  {
    controller: 'ContinuityController',
    entity: 'project_progress',
    label: 'Continuity Role',
    actions: {
      createRole: 'created',
      markOpened: 'opened',
      markClosed: 'closed',
    },
  },
  {
    controller: 'NotesController',
    entity: 'note',
    label: 'Shared Note',
    sharedOnly: true,
    actions: { create: 'created', update: 'updated' },
  },
  {
    controller: 'AutomationController',
    entity: 'automation_rule',
    label: 'Automation Rule',
    actions: {
      create: 'created',
      update: 'updated',
      remove: 'deleted',
      toggle: 'toggled',
      duplicate: 'duplicated',
      updateEscalation: 'escalation updated',
    },
  },
  {
    controller: 'ProjectPlannerController',
    entity: 'project_location',
    label: 'Project Location',
    idParam: 'locationId',
    actions: { createLocation: 'created', updateLocation: 'updated' },
  },
  {
    controller: 'DocumentRequirementsController',
    entity: 'document_requirement',
    label: 'Document Requirement',
    actions: { ...crud, markCompleted: 'completion updated' },
  },
  {
    controller: 'DocumentTypesController',
    entity: 'document_type',
    label: 'Document Type',
    actions: { ...crud },
  },
  {
    controller: 'ProjectPhaseController',
    entity: 'project_phase',
    label: 'Project Phase',
    actions: { ...crud },
  },
  {
    controller: 'ProjectTypeController',
    entity: 'project_type',
    label: 'Project Type',
    actions: { ...crud },
  },
  {
    controller: 'TermsController',
    entity: 'terms_template',
    label: 'Terms Template',
    actions: { ...crud, updateContent: 'content updated' },
  },
  {
    controller: 'UnitsController',
    entity: 'unit',
    label: 'Unit',
    actions: { ...crud },
  },
  {
    controller: 'LibraryController',
    path: 'workflow/library',
    entity: 'workflow_library',
    label: 'Workflow Library',
    actions: {
      createPhase: 'phase created',
      updatePhase: 'phase updated',
      createStep: 'step created',
      updateStep: 'step updated',
      addDeliverable: 'deliverable added',
      assignTeam: 'team assigned',
      removeTeam: 'team removed',
    },
  },
  {
    controller: 'RolesController',
    entity: 'role',
    label: 'Role',
    actions: { ...crud },
  },
  {
    controller: 'RolePermissionsController',
    entity: 'role',
    label: 'Role Permissions',
    actions: { grant: 'granted', bulkAssign: 'assigned', revoke: 'revoked' },
  },
  {
    controller: 'RoleAppsController',
    entity: 'role',
    label: 'Role Apps',
    actions: {
      grant: 'granted',
      bulkAssign: 'assigned',
      setForRole: 'updated',
      revoke: 'revoked',
    },
  },
  {
    controller: 'AppsController',
    entity: 'role',
    label: 'App Access',
    actions: { ...crud },
  },
  {
    controller: 'PermissionsController',
    entity: 'role',
    label: 'Permission',
    actions: { ...crud },
  },
  {
    controller: 'SettingsController',
    entity: 'company_setting',
    label: 'Company Setting',
    actions: { ...crud, upsert: 'saved' },
  },
];

export function frontendNotificationSource(
  controller: string,
  path: string,
  handler: string,
) {
  return FRONTEND_NOTIFICATION_SOURCES.find(
    (source) =>
      source.controller === controller &&
      (source.path === undefined || source.path === path) &&
      Object.hasOwn(source.actions, handler),
  );
}
