import React from 'react';
import { createRoot } from 'react-dom/client';
import { Provider } from 'react-redux';
import { configureStore } from '@reduxjs/toolkit';
import { BrowserRouter } from 'react-router-dom';
import { baseApi } from './src/store/baseApi';
import ProjectPlannerWorkspace from './src/pages/projects/ProjectPlannerWorkspace';
import './src/index.css';
const store = configureStore({ reducer: { [baseApi.reducerPath]: baseApi.reducer }, middleware: get => get().concat(baseApi.middleware) });
createRoot(document.getElementById('root')).render(<Provider store={store}><BrowserRouter><div style={{ padding: 16 }}><ProjectPlannerWorkspace /></div></BrowserRouter></Provider>);
