export enum ProjectBriefStatus {
  DRAFT = 'DRAFT',
  READY_FOR_DESIGN = 'READY_FOR_DESIGN',
  SIGNED_OFF = 'SIGNED_OFF',
  ARCHIVED = 'ARCHIVED',
}

export enum SiteAreaUnit {
  SQ_FT = 'SQ_FT',
  GAJ = 'GAJ',
  OTHER = 'OTHER',
}

export enum SiteType {
  FLAT = 'FLAT',
  FLOOR = 'FLOOR',
  KOTHI = 'KOTHI',
  RAW = 'RAW',
  OTHER = 'OTHER',
}

export enum SiteCondition {
  OCCUPIED = 'OCCUPIED',
  UNOCCUPIED = 'UNOCCUPIED',
}

export enum MaintenanceAppetite {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum BudgetGstStatus {
  INCLUDES_GST = 'INCLUDES_GST',
  EXCLUDES_GST = 'EXCLUDES_GST',
  NOT_SPECIFIED = 'NOT_SPECIFIED',
}

export enum FundingStage {
  SELF_FUNDED = 'SELF_FUNDED',
  LOAN = 'LOAN',
  NOT_SPECIFIED = 'NOT_SPECIFIED',
}

export enum StartDateStatus {
  FIXED = 'FIXED',
  PREFERRED = 'PREFERRED',
  NOT_SPECIFIED = 'NOT_SPECIFIED',
}

export enum WorkType {
  TURNKEY = 'TURNKEY',
  CONSULTANCY = 'CONSULTANCY',
  BUILDER_FINANCE = 'BUILDER_FINANCE',
  PMC_WORK = 'PMC_WORK',
  OTHER = 'OTHER',
}

export enum ServiceType {
  ARCHITECTURE_DESIGN = 'ARCHITECTURE_DESIGN',
  INTERIOR_DESIGN = 'INTERIOR_DESIGN',
  EXECUTION = 'EXECUTION',
  LABOUR_WORK = 'LABOUR_WORK',
  LANDSCAPE_DESIGN = 'LANDSCAPE_DESIGN',
  MATERIAL_PROCUREMENT = 'MATERIAL_PROCUREMENT',
  OTHER = 'OTHER',
}

export enum ProcurementCategory {
  CIVIL_BUILDING_MATERIAL = 'CIVIL_BUILDING_MATERIAL',
  METAL_WORK = 'METAL_WORK',
  AC_PIPING_DRAINAGE = 'AC_PIPING_DRAINAGE',
  ELECTRICAL = 'ELECTRICAL',
  PLUMBING = 'PLUMBING',
  NETWORKING = 'NETWORKING',
  TILES = 'TILES',
  SANITARY = 'SANITARY',
  CP_FITTINGS = 'CP_FITTINGS',
  CHEMICALS_ADHESIVES = 'CHEMICALS_ADHESIVES',
  STONE = 'STONE',
  MARBLE = 'MARBLE',
  GRANITE = 'GRANITE',
  DOORS = 'DOORS',
  CHAUKHATS = 'CHAUKHATS',
  HARDWARE = 'HARDWARE',
  PLY_WOOD = 'PLY_WOOD',
  PAINTS_POLISHES = 'PAINTS_POLISHES',
  FACADE_WORK = 'FACADE_WORK',
  FRP = 'FRP',
  MICRO_CONCRETE = 'MICRO_CONCRETE',
  OTHER = 'OTHER',
}

export enum StyleDirection {
  CONTEMPORARY = 'CONTEMPORARY',
  MINIMAL = 'MINIMAL',
  CLASSIC_TRADITIONAL = 'CLASSIC_TRADITIONAL',
  INDIAN_CONTEMPORARY = 'INDIAN_CONTEMPORARY',
  INDUSTRIAL = 'INDUSTRIAL',
  MID_CENTURY = 'MID_CENTURY',
  LUXE_OPULENT = 'LUXE_OPULENT',
  WARM_RUSTIC = 'WARM_RUSTIC',
  OTHER = 'OTHER',
}

export enum ProjectBriefAttachmentCategory {
  DRAWING = 'DRAWING',
  DOCUMENT = 'DOCUMENT',
  REFERENCE = 'REFERENCE',
  PHOTO = 'PHOTO',
  OTHER = 'OTHER',
}

export enum ProjectBriefDocumentType {
  SANCTIONED_PLAN = 'SANCTIONED_PLAN',
  ARCHITECTURAL_DRAWINGS = 'ARCHITECTURAL_DRAWINGS',
  STRUCTURAL_DRAWINGS = 'STRUCTURAL_DRAWINGS',
  MEP_LAYOUT = 'MEP_LAYOUT',
  COMPLETION_CERTIFICATE = 'COMPLETION_CERTIFICATE',
  SOCIETY_NOC = 'SOCIETY_NOC',
  PREVIOUS_DESIGNER_FILES = 'PREVIOUS_DESIGNER_FILES',
  NOTHING_AVAILABLE = 'NOTHING_AVAILABLE',
  OTHER = 'OTHER',
}
